---
region: 'eu-west-2'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"

component: 'test'

tags:
  ImportantTag: "important-value"

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

vpc_cidr: "10.1.0.0/16"

private_zone_id: 'Z2CDAFD23Q10HO'

custom_ami_id: "ami-3fb6bc5b"

cluster_name: 'test-cluster'
cluster_instance_ssh_public_key_path: "%{hiera('project_directory')}/config/secrets/keys/cluster/ssh.public"
cluster_instance_type: 't2.medium'
cluster_instance_amis:
  eu-west-2: "''"
cluster_instance_root_block_device_size: 40

cluster_minimum_size: 1
cluster_maximum_size: 3
cluster_desired_capacity: 2

security_groups: []

include_default_ingress_rule: "yes"
include_default_egress_rule: "yes"

allowed_cidrs:
  - '10.1.0.0/16'
egress_cidrs:
  - '10.1.0.0/16'
