---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
ami_id_in_region: "%{hiera('custom_ami_id')}"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  tags: "%{hiera('tags')}"

  cluster_name: "%{hiera('cluster_name')}"
  cluster_instance_ssh_public_key_path: "%{hiera('cluster_instance_ssh_public_key_path')}"
  cluster_instance_type: "%{hiera('cluster_instance_type')}"
  cluster_instance_amis: "%{hiera('cluster_instance_amis')}"
  cluster_instance_root_block_device_size: "%{hiera('cluster_instance_root_block_device_size')}"

  cluster_minimum_size: "%{hiera('cluster_minimum_size')}"
  cluster_maximum_size: "%{hiera('cluster_maximum_size')}"
  cluster_desired_capacity: "%{hiera('cluster_desired_capacity')}"

  include_default_ingress_rule: "%{hiera('include_default_ingress_rule')}"
  include_default_egress_rule: "%{hiera('include_default_egress_rule')}"

  security_groups: "%{hiera('security_groups')}"

  allowed_cidrs: "%{hiera('allowed_cidrs')}"
  egress_cidrs: "%{hiera('egress_cidrs')}"

  enable_container_insights: "%{hiera('enable_container_insights')}"

  protect_cluster_instances_from_scale_in: "%{hiera('protect_cluster_instances_from_scale_in')}"

  include_asg_capacity_provider: "%{hiera('include_asg_capacity_provider')}"
  asg_capacity_provider_manage_termination_protection: "%{hiera('asg_capacity_provider_manage_termination_protection')}"
  asg_capacity_provider_manage_scaling: "%{hiera('asg_capacity_provider_manage_scaling')}"
  asg_capacity_provider_minimum_scaling_step_size: "%{hiera('asg_capacity_provider_minimum_scaling_step_size')}"
  asg_capacity_provider_maximum_scaling_step_size: "%{hiera('asg_capacity_provider_maximum_scaling_step_size')}"
  asg_capacity_provider_target_capacity: "%{hiera('asg_capacity_provider_target_capacity')}"

